config/routes.rb
Rails.application.routes.draw do
  root 'chatroom#index'


  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post 'message',  to: 'messages#create'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
  scope :load_messages, -> { order(:created_at).last(10)}
end

app/models/user.rb
require 'bcrypt'
class User < ApplicationRecord
  has_secure_password
  has_many :messages
  validates :username, uniqueness: true, presence: true, length: { minimum: 3, maximum: 15}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = 'You must be logged in'
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user

  def index
    @messages = Message.load_messages
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user
  def create
    @message = current_user.messages.build(message_params)

    if @message.save
      ActionCable.server.broadcast 'chat-app', payload: message_payload
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_payload
    render(partial: 'chatroom/message', locals: {message: @message} )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]

  def new; end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'You are logged in!'
      redirect_to root_path
    else
      flash[:error] = 'Whoops, try again!'
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out!"
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = 'Already logged in!'
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatroom/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.username %></em>: <%= message.body %>
    </div>
  </div>
</div>

app/views/chatroom/index.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular users icon"></i>
  YACA!
</h2>
<div class="ui two column grid centered   ">
  <div class="ten wide column">
    <div class="ui fluid card chatbox">
      <div class="content" id='messages'>
        <div class="ui feed" id='message-container' >

          <%= render partial: 'message', collection: @messages %>

        </div>
      </div>
      <div class="extra content">
        <%= form_for Message.new, html: {class: 'ui reply form', role: 'form'}, url: message_path, remote: true do |f| %>
        <div class="field">
          <div class="ui fuild icon input">
            <%= f.text_field :body  %>
            <%= f.button '<i class="bordered teal inverted edit icon"></i>'.html_safe %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="four wide column ">
    <div class="ui vertical menu">
      <div class="ui fluid card chatbox">
        <div class="content">
          <a class="active teal item">
            Inbox
            <div class="ui teal left pointing label">1</div>
          </a>
          <a class="item">
            Spam
            <div class="ui label">51</div>
          </a>
          <a class="item">
            Updates
            <div class="ui label">1</div>
          </a>
          <div class="item">
            <div class="ui transparent icon input">
              <input type="text" placeholder="Search mail...">
              <i class="search icon"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_menu.html.erb
 <div class="ui tiny menu">
     <div class="ui container">
     <%= link_to "Chat", root_path, class: 'item'  %>
     </a>
     <a class="item">
       Messages
     </a>
     <div class="right menu">
       <div class="ui dropdown item">
         Account <i class="dropdown icon"></i>
         <div class="menu">
           <a class="item">Log out</a>
           <a class="item">Log in</a>
           <a class="item">Sign up</a>
         </div>
       </div>

       <% unless logged_in? %>
        <div class="item">
          <%= link_to "Log in", login_path, class: 'ui primary button teal' %>
        </div>
        <% else %>
        <div class="item">
          <%= link_to "Log out", logout_path, method: :delete, class: 'ui primary button teal' %>
        </div>
       <% end %>

     </div>
     </div>
 </div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="ui <%= message_type %> four wide message transition">
    <i class="close icon"></i>
    <div class="header">
      <p><%= message_content %></p>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yaca</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui tiny menu">
      <div class="ui container">
        <%= render 'layouts/menu' %>
      </div>
     </div>
    <div class="ui container">
     <%= render 'layouts/messages' %>
     <%= yield %>
    </div>
  </body>
</html>